name: xrefcoord
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Required dependencies
  - python=3.10
  - xarray
  - zarr
  # Optional dependencies
  - fsspec
  - s3fs
  - dask
  - rioxarray
  - rasterio
  - imagecodecs
  - matplotlib
  - tifffile
  - xarray-datatree
  # Development dependencies
  - git
  - earthaccess
  - jupyter
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mypy
  # Pip dependencies
  - pip
  - pip:
      - git+https://github.com/fsspec/filesystem_spec
      - git+https://github.com/fsspec/kerchunk.git
      - -e ../.
