name: xrefcoord
channels:
  - conda-forge
  - nodefaults
dependencies:
  - fsspec
  - dask
  - git
  - hypothesis
  - imagecodecs
  - earthaccess
  - jupyter
  - numpy
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mypy
  - python=3.10
  - rasterio
  - rioxarray
  - s3fs
  - scipy
  - tifffile
  - xarray
  - zarr
  - pip:
      - git+https://github.com/fsspec/filesystem_spec
      - git+https://github.com/fsspec/kerchunk.git
      - git+https://github.com/xarray-contrib/datatree.git
      - -e ../.
