name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          # fetch all history so that setuptools-scm works
          fetch-depth: 0

      # Install Mambaforge with conda-forge dependencies
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: envs/xrefcoord
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,nodefaults
          channel-priority: strict
          miniforge-version: latest
          miniforge-variant: Mambaforge
          mamba-version: '*'
          run-post: false
          use-mamba: true

      - name: Install dependencies
        run: |
          mamba install pytest pytest-cov pytest-mypy

      - name: List installed packages
        run: mamba list

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip list

      - name: Tests # run tests (includes mypy checks and coverage export)
        run: |
          python -m pytest
